### PR TITLE
Change for running as a non-root user

### PR DESCRIPTION
**Pull request by arthurbarr**

### CODE REVIEW

**Comment by andrejpetras** [comment]
Hi,
I tried the pull request on the openshift. I got this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e8e46]
  |  
  | goroutine 1 [running]:
  | github.com/ibm-messaging/mq-container/internal/logger.(*Logger).Debugf(0x0, 0x58be53, 0x1f, 0xc42006fe20, 0x1, 0x1)
  | /go/src/github.com/ibm-messaging/mq-container/internal/logger/logger.go:127 +0x26
  | main.logTermination(0xc4200103b0, 0x1, 0x1)
  | /go/src/github.com/ibm-messaging/mq-container/cmd/runmqdevserver/main.go:103 +0x16e
  | main.doMain(0x5241ea, 0xc42009e210)
  | /go/src/github.com/ibm-messaging/mq-container/cmd/runmqdevserver/main.go:114 +0xae
  | main.main()
  | /go/src/github.com/ibm-messaging/mq-container/cmd/runmqdevserver/main.go:166 +0x26
```


Dockerfile:
```
FROM andrejpetras/mqadvanced-server-dev:9.1.1.0-2
COPY config/* /etc/mqm/
ENV LICENSE=accept
USER mqm
ENV MQ_QMGR_NAME=MY_MQ
ENTRYPOINT ["runmqserver"]
```

**Comment by arthurbarr** [comment]
@andrejpetras the entry point in your Dockerfile says "runmqserver", but the error is from "runmqdevserver".  Normally, in an MQ Advanced for Developers image, "runmqdevserver" is the entry point, and that calls "runmqserver" at the end.

Can you please also supply the command you used when you ran the container?  There are some specific settings which are required now that we're running as a non-root user.

**Comment by andrejpetras** [comment]
Yes you are right. I try runmqdevserver, runmqserver.
I also try to use LOG_FORMAT json, basic and DEBUG true

What do I need to set up for non-root?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50a546]

goroutine 1 [running]:
github.com/ibm-messaging/mq-container/internal/logger.(*Logger).Debugf(0x0, 0x87a609, 0x1f, 0xc420085df8, 0x1, 0x1)
	/go/src/github.com/ibm-messaging/mq-container/internal/logger/logger.go:127 +0x26
main.logTermination(0xc4201ce070, 0x1, 0x1)
	/go/src/github.com/ibm-messaging/mq-container/cmd/runmqserver/logging.go:45 +0x16e
main.doMain(0x0, 0x0)
	/go/src/github.com/ibm-messaging/mq-container/cmd/runmqserver/main.go:40 +0x178
main.main()
	/go/src/github.com/ibm-messaging/mq-container/cmd/runmqserver/main.go:190 +0x22
```

```

  | panic: runtime error: invalid memory address or nil pointer dereference
-- | --
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e8e46]
  |  
  | goroutine 1 [running]:
  | github.com/ibm-messaging/mq-container/internal/logger.(*Logger).Debugf(0x0, 0x58be53, 0x1f, 0xc42006fe20, 0x1, 0x1)
  | /go/src/github.com/ibm-messaging/mq-container/internal/logger/logger.go:127 +0x26
  | main.logTermination(0xc4200103b0, 0x1, 0x1)
  | /go/src/github.com/ibm-messaging/mq-container/cmd/runmqdevserver/main.go:103 +0x16e
  | main.doMain(0x5241ea, 0xc42009e210)
  | /go/src/github.com/ibm-messaging/mq-container/cmd/runmqdevserver/main.go:114 +0xae
  | main.main()
  | /go/src/github.com/ibm-messaging/mq-container/cmd/runmqdevserver/main.go:166 +0x26

```

**Comment by arthurbarr** [comment]
If I run `docker run --rm -ti -e LOG_FORMAT="json" -e LICENSE=accept -e DEBUG=true mqadvanced-server-dev:9.1.1.0-x86_64-ubuntu-16.04`, then it works fine for me:

```
2019-02-19T15:13:05.815Z Set password for "admin" user
2019-02-19T15:13:05.830Z Using queue manager name: 9460f0f7bdbe
2019-02-19T15:13:05.830Z Detected current user as: &{999 999 mqm  /home/mqm}+
2019-02-19T15:13:05.830Z CPU architecture: amd64
2019-02-19T15:13:05.831Z Linux kernel version: 4.15.0
2019-02-19T15:13:05.831Z Container runtime: docker
2019-02-19T15:13:05.831Z Base image: Ubuntu 16.04.5 LTS...
```

Same is true if I set `LOG_FORMAT="json"`

**Comment by andrejpetras** [comment]
@arthurbarr again, you are right ;).  I did not try it at all on my local laptop. On the local laptop it works  fine for me. My errors are from the OpenShift.

Result: The pull-request works fine for me!

**Pull request merged**
